# Generated by Django 4.2.9 on 2026-02-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(default='Nicolas Garlinski', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hero_image', models.URLField(blank=True)),
                ('hero_image_alt', models.CharField(blank=True, max_length=200)),
                ('is_new', models.BooleanField(default=False)),
                ('nav_label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PostContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lead', 'Lead Paragraph'), ('text', 'Text Paragraph'), ('image', 'Image'), ('blockquote', 'Blockquote')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('blockquote_footer', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='blog.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
